import { Post, CreatePostData } from '@domain/entities/Post';
import { PostRepository } from '@domain/repositories/PostRepository';

/**
 * CreatePost use case handles the business logic for creating new blog posts.
 * This class is part of the application layer and orchestrates domain logic.
 */
export class CreatePost {
  constructor(private readonly postRepository: PostRepository) {}

  /**
   * Executes the create post use case
   * @param postData - The data required to create a new post
   * @returns Promise resolving to the created post
   */
  async execute(postData: CreatePostData): Promise<Post> {
    // Create timestamp
    const createdAt = new Date().toISOString();
    
    // Build the complete post entity
    // Note: id will be generated by MongoDB and returned by the repository
    const post: Post = {
      id: '', // This will be overwritten by MongoDB's _id
      title: postData.title,
      content: postData.content,
      author: postData.author || null,
      createdAt,
      updatedAt: null,
    };

    // Persist the post using the repository
    return await this.postRepository.create(post);
  }
}